/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradletest.app;

import gradletest.list.LinkedList;

import static gradletest.utilities.StringUtils.join;
import static gradletest.utilities.StringUtils.split;
import static gradletest.app.MessageUtils.getMessage;


public class App {
    public static void main(String[] args) {
        System.out.print("HELLO WORLD");
    }
}
